### ISSUE TITLE
CFT parameter help 

### ISSUE THREAD

**Issue by roncewind** [Senzing/aws-marketplace-evaluation#13]
Other CFTs have help pages like:  https://hub.senzing.com/aws-cloudformation-database-cluster   This will need to be created and maintained for the CFTs available in this repo.  IF that's how we are going to provide parameter help.  No matter how we do it, we need to review and update the parameter help for the CFTs in this repo

See https://github.com/Senzing/aws-cloudformation-database-cluster/issues/17

**Comment by docktermj** [comment]
Blocked until a cloudformation.yaml template is added to main branch.

Once `cloudformation.yaml` is present, a copy of https://github.com/Senzing/aws-cloudformation-ecs-senzing-stack-basic/blob/main/docs/README.md will be used as the bases of `docs/README.md`.   Then it will be tailored to match `cloudformation.yaml`.
